name: Working Directory Workflow
on: [push]
jobs: 
    working-directory: 
        runs-on: ubuntu-latest
        steps:
            - name: Display WD
              run: |
                pwd
                ls -a 
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE

    working-directory-windows: 
        runs-on: windows-latest
        steps:
            - name: Display WD
              run: |
                 Get-Location
                 dir
                 echo $env:GITHUB_SHA
                 echo $env:GITHUB_REPOSITORY
                 echo $env:GITHUB_WORKSPAC            
              
              


